// Code generated by mockery v2.42.0. DO NOT EDIT.

package walletmock

import (
	context "context"

	entity "github.com/safayildirim/wallet-management-service/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockWalletRepository is an autogenerated mock type for the Repository type
type MockWalletRepository struct {
	mock.Mock
}

type MockWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepository) EXPECT() *MockWalletRepository_Expecter {
	return &MockWalletRepository_Expecter{mock: &_m.Mock}
}

// CreateWallet provides a mock function with given fields: ctx, _a1
func (_m *MockWalletRepository) CreateWallet(ctx context.Context, _a1 *entity.Wallet) (*entity.Wallet, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 *entity.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Wallet) (*entity.Wallet, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Wallet) *entity.Wallet); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Wallet) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletRepository_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Wallet
func (_e *MockWalletRepository_Expecter) CreateWallet(ctx interface{}, _a1 interface{}) *MockWalletRepository_CreateWallet_Call {
	return &MockWalletRepository_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, _a1)}
}

func (_c *MockWalletRepository_CreateWallet_Call) Run(run func(ctx context.Context, _a1 *entity.Wallet)) *MockWalletRepository_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Wallet))
	})
	return _c
}

func (_c *MockWalletRepository_CreateWallet_Call) Return(_a0 *entity.Wallet, _a1 error) *MockWalletRepository_CreateWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_CreateWallet_Call) RunAndReturn(run func(context.Context, *entity.Wallet) (*entity.Wallet, error)) *MockWalletRepository_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWallet provides a mock function with given fields: ctx, id
func (_m *MockWalletRepository) DeleteWallet(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepository_DeleteWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWallet'
type MockWalletRepository_DeleteWallet_Call struct {
	*mock.Call
}

// DeleteWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockWalletRepository_Expecter) DeleteWallet(ctx interface{}, id interface{}) *MockWalletRepository_DeleteWallet_Call {
	return &MockWalletRepository_DeleteWallet_Call{Call: _e.mock.On("DeleteWallet", ctx, id)}
}

func (_c *MockWalletRepository_DeleteWallet_Call) Run(run func(ctx context.Context, id uint)) *MockWalletRepository_DeleteWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockWalletRepository_DeleteWallet_Call) Return(_a0 error) *MockWalletRepository_DeleteWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepository_DeleteWallet_Call) RunAndReturn(run func(context.Context, uint) error) *MockWalletRepository_DeleteWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetWallet provides a mock function with given fields: ctx, id
func (_m *MockWalletRepository) GetWallet(ctx context.Context, id uint) (*entity.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 *entity.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWallet'
type MockWalletRepository_GetWallet_Call struct {
	*mock.Call
}

// GetWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockWalletRepository_Expecter) GetWallet(ctx interface{}, id interface{}) *MockWalletRepository_GetWallet_Call {
	return &MockWalletRepository_GetWallet_Call{Call: _e.mock.On("GetWallet", ctx, id)}
}

func (_c *MockWalletRepository_GetWallet_Call) Run(run func(ctx context.Context, id uint)) *MockWalletRepository_GetWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockWalletRepository_GetWallet_Call) Return(_a0 *entity.Wallet, _a1 error) *MockWalletRepository_GetWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetWallet_Call) RunAndReturn(run func(context.Context, uint) (*entity.Wallet, error)) *MockWalletRepository_GetWallet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepository creates a new instance of MockWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepository {
	mock := &MockWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
