// Code generated by mockery v2.42.0. DO NOT EDIT.

package walletmock

import (
	context "context"

	entity "github.com/safayildirim/wallet-management-service/internal/wallet/entity"
	mock "github.com/stretchr/testify/mock"

	request "github.com/safayildirim/wallet-management-service/internal/wallet/request"
)

// MockWalletService is an autogenerated mock type for the Service type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// CreateWallet provides a mock function with given fields: ctx, _a1
func (_m *MockWalletService) CreateWallet(ctx context.Context, _a1 *request.CreateWalletRequest) (*entity.Wallet, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 *entity.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.CreateWalletRequest) (*entity.Wallet, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.CreateWalletRequest) *entity.Wallet); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.CreateWalletRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletService_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *request.CreateWalletRequest
func (_e *MockWalletService_Expecter) CreateWallet(ctx interface{}, _a1 interface{}) *MockWalletService_CreateWallet_Call {
	return &MockWalletService_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, _a1)}
}

func (_c *MockWalletService_CreateWallet_Call) Run(run func(ctx context.Context, _a1 *request.CreateWalletRequest)) *MockWalletService_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.CreateWalletRequest))
	})
	return _c
}

func (_c *MockWalletService_CreateWallet_Call) Return(_a0 *entity.Wallet, _a1 error) *MockWalletService_CreateWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_CreateWallet_Call) RunAndReturn(run func(context.Context, *request.CreateWalletRequest) (*entity.Wallet, error)) *MockWalletService_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWallet provides a mock function with given fields: ctx, id
func (_m *MockWalletService) DeleteWallet(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_DeleteWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWallet'
type MockWalletService_DeleteWallet_Call struct {
	*mock.Call
}

// DeleteWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockWalletService_Expecter) DeleteWallet(ctx interface{}, id interface{}) *MockWalletService_DeleteWallet_Call {
	return &MockWalletService_DeleteWallet_Call{Call: _e.mock.On("DeleteWallet", ctx, id)}
}

func (_c *MockWalletService_DeleteWallet_Call) Run(run func(ctx context.Context, id uint)) *MockWalletService_DeleteWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockWalletService_DeleteWallet_Call) Return(_a0 error) *MockWalletService_DeleteWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_DeleteWallet_Call) RunAndReturn(run func(context.Context, uint) error) *MockWalletService_DeleteWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetWallet provides a mock function with given fields: ctx, id
func (_m *MockWalletService) GetWallet(ctx context.Context, id uint) (*entity.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 *entity.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWallet'
type MockWalletService_GetWallet_Call struct {
	*mock.Call
}

// GetWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockWalletService_Expecter) GetWallet(ctx interface{}, id interface{}) *MockWalletService_GetWallet_Call {
	return &MockWalletService_GetWallet_Call{Call: _e.mock.On("GetWallet", ctx, id)}
}

func (_c *MockWalletService_GetWallet_Call) Run(run func(ctx context.Context, id uint)) *MockWalletService_GetWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockWalletService_GetWallet_Call) Return(_a0 *entity.Wallet, _a1 error) *MockWalletService_GetWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetWallet_Call) RunAndReturn(run func(context.Context, uint) (*entity.Wallet, error)) *MockWalletService_GetWallet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
